/**
* Description : This file contains all common functions for PerkpalRestDataAccess Service
**/

/**
 * Importing all the required modules
 */
const lodash = require('lodash');

const config = require("../../config");
const messages = require("../utils/messages");
const apiConfig = require("../../api.config.json");


/**
 * Initializing objects for all the imported classes
 */
const ConfigObject = new config();
const Config = ConfigObject.getConfig();
const Messages = new messages();

/**
 * Initializing the database client object
 */
let databaseClient = {};

module.exports = class commons {

	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 04 2022
	* ModifiedBy   : Dinesh
	* ModifiedTime : Dec 04 2022
	* Description  : This function gets the current datetime
	**/
	async getCurrentDateTime() {
		try {
			return new Date().toISOString();
		} catch (error) {
			console.log(error);
		}
	}


	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 23 2022
	* ModifiedBy   : Dinesh
	* ModifiedTime : Dec 23 2022
	* Description  : This function generates service response object for all APIs
	**/
	generateControllerOutput(response, data, status, message, endpoint) {
		let output = {
			outputResponse: data,
			serviceResponse: {
				status: status,
				message: message,
				timestamp: new Date().toLocaleString(),
				endpoint: endpoint
			}
		};
		if (response === null) {
			return output;
		} else {
			response.status(status);
			return output;
		}
	}


	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 23 2022
	* ModifiedBy   : Dinesh
	* ModifiedTime : Dec 23 2022
	* Description  : This function generates service response o
	**/
	generateServiceOutput(data, status, message) {
		let output = {
			data: data,
			status: status,
			message: message
		};
		return output
	}


	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 23 2022
	* ModifiedBy   : Dinesh
	* ModifiedTime : Dec 23 2022
	* Description  : This function generates service response o
	**/
	generateServiceOutputForAvalibalityNotEnabled() {
		let output = this.generateServiceOutput(null, 400, Messages.MESSAGE_AVAILABILITY_NOT_ENABLED);
		return output
	}

	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 26 2022
	* ModifiedBy   : Dinesh
	* ModifiedTime : Dec 26 2022
	* Description  : This function parses the JSON with bigint in the object 
	* (Without object generated by prisma cannot be converted to json)
	**/
	parseControllerOutput(input) {
		const output = JSON.parse(JSON.stringify(input, (_, v) => typeof v === "bigint" ? `${v}n` : v).replace(/"(-?\d+)n"/g, (_, a) => a));
		return output;
	}


	/**
	* Description  : This function executes controller functions
	**/
	async executeController(request, response, apiID, serviceFunction) {

		const merchantKey = request.headers.merchantkey;
		const tenantKey = request.headers.tenantkey;
		const authKey = request.headers.authkey;
		const applicationKey = request.headers.applicationkey;
		const instanceKey = request.headers.instancekey;
		const serviceKey = request.headers?.servicekey;
		const serviceTypeKey = request.headers?.servicetypekey;

		// Initializing global variables
		let executionStartTime = null; let executionEndTime = null; let serviceOutput = null;
		let islogEnabled = Config.SERVICE_REGISTRY.IS_BAAS_LOG_ENABLED !== undefined ? JSON.parse(Config.SERVICE_REGISTRY.IS_BAAS_LOG_ENABLED) : Config.SERVICE_REGISTRY.IS_BAAS_LOG_ENABLED
		try {
			executionStartTime = await this.getCurrentDateTime();
			console.log(`${apiConfig[apiID].Name} API EXECUTION STARTS AT (${executionStartTime})`);

			this.validateRequestHeaders(merchantKey, tenantKey, authKey, applicationKey, instanceKey, serviceKey);

			const serviceConfig = Config.SERVICE_CONNECTOR.SQLSERVER[`${merchantKey}@${tenantKey}`]
			if (!serviceConfig) {
				throw this.generateServiceOutput(
					null,
					400,
					"No matching service connector configured for the given MerchantKey & TenantKey in the Headers"
				)
			}

			const databaseConnector = databaseClient[`${merchantKey}@${tenantKey}`]

			if (apiID.includes("readone") || apiID.includes("deleteone")) {
				serviceOutput = await serviceFunction(databaseConnector, apiID, apiConfig[apiID], request.params);
			}
			else {
				serviceOutput = await serviceFunction(databaseConnector, apiID, apiConfig[apiID], request.body);
			}

			console.log(`${apiConfig[apiID].Name} SERVICE OUTPUT : (${serviceOutput})`);

			const controllerOutput = this.generateControllerOutput(response, serviceOutput.data.result, serviceOutput.status, serviceOutput.message, request.originalUrl);
			response.json(this.parseControllerOutput(controllerOutput));
			executionEndTime = await this.getCurrentDateTime();
			console.log(`${apiConfig[apiID].Name} API EXECUTION ENDS AT (${executionEndTime})`);

			const memoryUsageAfterResponse = process.memoryUsage();
			const memoryUsageBeforeResponse = request.memoryBefore;

			const logData = {
				"metaData": {
					/** Organization Information */
					"Merchant": { "MerchantKey": merchantKey },
					"Tenant": { "TenantKey": tenantKey },

					/** Client Information */

					"ClientApplication": { "ClientApplicationKey": applicationKey },
					"ClientEnvironmentType": { "ClientEnvironmentTypeKey": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_KEY },
					"ClientInstance": { "ClientInstanceKey": instanceKey },
					"ClientServiceType": { "ClientServiceTypeKey": serviceTypeKey },
					"ClientService": { "ClientServiceKey": serviceKey },

					/** Service Information */

					"Application": { "ApplicationKey": Config.APPLICATION.APPLICATION_KEY, "ApplicationName": Config.APPLICATION.APPLICATION_NAME },
					"EnvironmentType": { "EnvironmentTypeKey": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_KEY, "EnvironmentTypeName": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_NAME },
					"Instance": { "InstanceKey": Config.INSTANCE.INSTANCE_KEY, "InstanceName": Config.INSTANCE.INSTANCE_NAME, "InstanceURL": Config.INSTANCE.INSTANCE_URL },
					"ServiceType": { "ServiceTypeKey": Config.SERVICE_TYPE.SERVICE_TYPE_KEY, "ServiceTypeName": Config.SERVICE_TYPE.SERVICE_TYPE_NAME },
					"Service": { "ServiceKey": Config.SERVICE_KEY, "ServiceName": Config.SERVICE_NAME, "ServiceURL": Config.SERVICE_IP_URL },

					/** User Information */
					"CreatedAuth": { "AuthKey": authKey }
				},
				"inputData": {
					"EndpointKey": apiID,
					"EndpointName": apiConfig[apiID].Name,
					"EndpointMethod": apiConfig[apiID].Method,
					"EndpointURL": apiConfig[apiID].Endpoint,
					"EndpointCode": apiID,
					"Header": JSON.stringify(request.headers),
					"Request": apiConfig[apiID].IsRequestLogEnabled ? JSON.stringify(request.body) : JSON.stringify({ message: "API Request log has been disabled" }),
					"Response": apiConfig[apiID].IsResponseLogEnabled ? JSON.stringify(controllerOutput) : JSON.stringify({ message: "API Response log has been disabled" }),
					"StatusCode": controllerOutput?.serviceResponse?.status,
					"Message": controllerOutput?.serviceResponse?.message,
					"ExecutionStartTime": executionStartTime,
					"ExecutionEndTime": executionEndTime,
					"EndpointProcessMemory": memoryUsageAfterResponse.rss - memoryUsageBeforeResponse.rss, // total memory used by the process in physical RAM
					"EndpointTotalHeapMemory": memoryUsageAfterResponse.heapTotal - memoryUsageBeforeResponse.heapTotal, //memory has been allocated for the heap 
					"EndpointUsedHeapMemory": memoryUsageAfterResponse.heapUsed - memoryUsageBeforeResponse.heapUsed, //amount of memory actively used in the heap
					"EndpointExternalMemory": memoryUsageAfterResponse.external - memoryUsageBeforeResponse.external,
					"EndpointRegistry": {
						"QueryInfo": serviceOutput.data.query ? (JSON.stringify(serviceOutput.data.query)).toString() : null
					}
				}
			}

			if (islogEnabled) {
				/** Calling the Baas Log SDK */
				BaasLogSDK.Service.storeLog(logData).then(output => {
					console.log(`BAAS LOG : STORED THE API LOG SUCCUSSFULLY IN BAAS LOG : `, output)
				}).catch(output => {
					console.log(`BAAS LOG : FAILED TO STORED THE API LOG SUCCUSSFULLY IN BAAS LOG : `, output)
				})
			}

			console.info({
				requestURL: request.originalUrl,
				requestMethod: request.method,
				requestHeaders: request.headers,
				requestBody: JSON.stringify(request.body),
				responseBody: JSON.stringify(this.parseControllerOutput(controllerOutput)),
				executionStartTime: executionStartTime,
				executionEndTime: executionEndTime
			});
		} catch (error) {
			console.error("ERROR IN EXECUTE CONTROLLER FUNCTION : ", error)
			if (error.status == null) {
				let controllerOutput = this.generateControllerOutput(response, null, 500, error.message, request.originalUrl);
				response.json(controllerOutput);
			}
			let controllerOutput = this.generateControllerOutput(response, error.output ? error.data : null, error.status, error.message, request.originalUrl);
			response.json(this.parseControllerOutput(controllerOutput));
			executionEndTime = await this.getCurrentDateTime();

			const memoryUsageAfterResponse = process.memoryUsage();

			const logData = {
				"metaData": {
					/** Organization Information */
					"Merchant": { "MerchantKey": merchantKey },
					"Tenant": { "TenantKey": tenantKey },

					/** Client Information */

					"ClientApplication": { "ClientApplicationKey": applicationKey },
					"ClientEnvironmentType": { "ClientEnvironmentTypeKey": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_KEY },
					"ClientInstance": { "ClientInstanceKey": instanceKey },
					"ClientServiceType": { "ClientServiceTypeKey": serviceTypeKey },
					"ClientService": { "ClientServiceKey": serviceKey },

					/** Service Information */

					"Application": { "ApplicationKey": Config.APPLICATION.APPLICATION_KEY, "ApplicationName": Config.APPLICATION.APPLICATION_NAME },
					"EnvironmentType": { "EnvironmentTypeKey": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_KEY, "EnvironmentTypeName": Config.ENVIRONMENT_TYPE.ENVIRONMENT_TYPE_NAME },
					"Instance": { "InstanceKey": Config.INSTANCE.INSTANCE_KEY, "InstanceName": Config.INSTANCE.INSTANCE_NAME, "InstanceURL": Config.INSTANCE.INSTANCE_URL },
					"ServiceType": { "ServiceTypeKey": Config.SERVICE_TYPE.SERVICE_TYPE_KEY, "ServiceTypeName": Config.SERVICE_TYPE.SERVICE_TYPE_NAME },
					"Service": { "ServiceKey": Config.SERVICE_KEY, "ServiceName": Config.SERVICE_NAME, "ServiceURL": Config.SERVICE_IP_URL },
					/** User Information */
					"CreatedAuth": { "AuthKey": authKey }
				},
				"inputData": {
					"EndpointKey": apiID,
					"EndpointName": apiConfig[apiID].Name,
					"EndpointMethod": apiConfig[apiID].Method,
					"EndpointURL": apiConfig[apiID].Endpoint,
					"EndpointCode": apiID,
					"Header": JSON.stringify(request.headers),
					"Request": JSON.stringify(request.body),
					"Response": JSON.stringify(controllerOutput),
					"StatusCode": controllerOutput?.serviceResponse?.status,
					"Message": controllerOutput?.serviceResponse?.message,
					"ExecutionStartTime": executionStartTime,
					"ExecutionEndTime": executionEndTime,
					"EndpointProcessMemory": memoryUsageAfterResponse.rss - request.memoryBefore.rss, // total memory used by the process in physical RAM
					"EndpointTotalHeapMemory": memoryUsageAfterResponse.heapTotal - request.memoryBefore.heapTotal, //memory has been allocated for the heap 
					"EndpointUsedHeapMemory": memoryUsageAfterResponse.heapUsed - request.memoryBefore.heapUsed, //amount of memory actively used in the heap
					"EndpointExternalMemory": memoryUsageAfterResponse.external - request.memoryBefore.external,
					"EndpointRegistry": {
						"QueryInfo": error.data?.query ? (JSON.stringify(error.data?.query)).toString() : null
					}
				}
			}
			if (islogEnabled) {
				/** Calling the Baas Log SDK */
				BaasLogSDK.Service.storeLog(logData).then(output => {
					console.log(`BAAS LOG : STORED THE API LOG SUCCUSSFULLY IN BAAS LOG : `, output)
				}).catch(output => {
					console.log(`BAAS LOG : FAILED TO STORED THE API LOG SUCCUSSFULLY IN BAAS LOG : `, output)
				})
			}

			console.error({
				requestURL: request.originalUrl,
				requestMethod: request.method,
				requestHeaders: request.headers,
				requestBody: JSON.stringify(request.body),
				responseBody: JSON.stringify(this.parseControllerOutput(controllerOutput)),
				executionStartTime: executionStartTime,
				executionEndTime: executionEndTime
			});
		}
	}

	/**
	 * CreatedBy    : Gayathri
	 * CreatedTime  : Dec 5 2024
	 * ModifiedBy   : Gayathri
	 * ModifiedTime : Dec 5 2024
	 * Description  : Tracks and logs prisma queries
	 */

	queryLogger = (databaseConnector) => {
		const isQueryLogEnabled = Config.SERVICE_REGISTRY.IS_QUERY_LOG_ENABLED !== undefined ? JSON.parse(Config.SERVICE_REGISTRY.IS_QUERY_LOG_ENABLED) : Config.SERVICE_REGISTRY.IS_QUERY_LOG_ENABLED
		let queryInfo = [];
		if (isQueryLogEnabled) {

			let queryOrder = 0;

			databaseConnector.$on('query', (e) => {
				queryOrder += 1;
				queryInfo.push({
					queryOrder,
					query: e.query,
					queryDuration: `${e.duration} ms`,
				});
			});
			return queryInfo;
		}
	};

	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Dec 26 2022
	* ModifiedBy   : Gayathri
	* ModifiedTime : Dec 02 2024
	* Description  : This function generates the prisma database connection and stores in a variable
	**/
	async generateDefaultDatabaseConnector() {
		try {

			const serviceConnectors = Config.SERVICE_CONNECTOR;

			const isStaticDBConnectionEnabled = Config.SERVICE_REGISTRY.IS_STATIC_DB_CONNECTION_ENABLED !== undefined ? JSON.parse(Config.SERVICE_REGISTRY.IS_STATIC_DB_CONNECTION_ENABLED) : Config.SERVICE_REGISTRY.IS_STATIC_DB_CONNECTION_ENABLED

			for (const serviceConnectorType in serviceConnectors) {

				if (serviceConnectorType === "POSTGRESQL" || serviceConnectorType === "COCKROACHDB" || serviceConnectorType === "MARIADB" || serviceConnectorType === "SQLSERVER" || serviceConnectorType === "MONGODB" || serviceConnectorType === "MYSQL" || serviceConnectorType === "SQLITE") {
					const serviceTenantConnectors = serviceConnectors[serviceConnectorType];

					for (const serviceTenantConnector in serviceTenantConnectors) {

						const serviceConfig = serviceTenantConnectors[serviceTenantConnector];

						console.log(serviceConfig, `Service Config for Type: ${serviceConnectorType}, Key: ${serviceTenantConnector}`);

						let databaseURL = serviceConfig.CONNECTOR_URL;
						let databaseClientObject = new PrismaClient({
							log: ['query'],
							datasources: {
								db: {
									url: databaseURL,
								},
							},
						});

						databaseClient[`${serviceTenantConnector}`] = databaseClientObject;

						console.log(`${Messages.MESSAGE_CONNECTED_TO_DEFAULT_DATABASE} for DB : ${databaseURL}`);

						if (isStaticDBConnectionEnabled) {
							/**
							 * Always one connection object is made using the first DB URL in the config
							 * Multiple connection with one ORM is unstable
							 */
							break
						}
					}

					/**
					 * Make sure only one Database Type is tied to one DAL
					 */
					break
				}
			}
		} catch (error) {
			console.error("Error generating database connectors:", error.message);
			throw { output: null, status: 500, message: error.message };
		}

	}

	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Jan 09 2023
	* ModifiedBy   : Dinesh
	* ModifiedTime : Jan 09 2023
	* Description  : This function returns relevant query object for given request for read multiple api 
	**/
	generatePrismaFindManyInput(input) {
		let output
		try {
			let { filter, fields, limit, page, sort } = input
			page = limit * page;
			if (lodash.isEmpty(input)) {
				throw { data: null, status: 400, message: Messages.MESSAGE_INVALID_FILTER_OBJECT }
			} else if (fields && Object.keys(fields).length === 0) {
				output = {
					where: filter,
					take: limit,
					skip: page,
					orderBy: sort,
					include: input?.include ? (Object.keys(input.include).length === 0 ? undefined : input?.include) : undefined
				}
			}
			else {
				output = {
					where: filter,
					select: fields,
					take: limit,
					skip: page,
					orderBy: sort,
					include: input?.include ? (Object.keys(input.include).length === 0 ? undefined : input?.include) : undefined
				}
			}
			return output
		} catch (error) {
			throw { data: null, status: 500, message: error.message }
		}
	}

	/**
	* CreatedBy    : Dinesh
	* CreatedTime  : Jan 09 2023
	* ModifiedBy   : Dinesh
	* ModifiedTime : Jan 09 2023
	* Description  : This function returns relevant query object for given request for read count api 
	**/

	generatePrismaAggregateInput(input) {
		let output
		try {
			let { filter } = input
			output = {
				where: filter,
				_count: true
			}
			return output
		} catch (error) {
			throw { data: null, status: 500, message: error.message }
		}
	}

	/**
	 * CreatedBy    : Uma Kohila
	 * CreatedTime  : JULY 26 2024
	 * ModifiedBy   : Uma Kohila
	 * ModifiedTime : JULY 26 2024
	 * Description  : This function returns relevant query object for given request for Sum by Group 
	*/
	generatePrismaGroupByInput(input) {
		let output
		try {
			let { filter, fields, groupBy } = input
			output = {
				where: filter,
				_sum: fields,
				_count: true,
				by: groupBy
			}
			return output
		} catch (error) {
			throw { data: null, status: 500, message: error.message }
		}
	}
};